Add calc_adc_segments for segmentation of long ADC.
imr-framework/pypulseq pull request #196
Opened 2024-08-26 09:32 UTC by felixlandmeyer

Adds `calc_adc_segments` to the `make_adc.py`.
Adds `adc_samples_limit` and `adc_samples_divisor` to `system` in `opts`.
Test function `test_calc_adc_segments` compares output to the matlab output from [calcAdcSeg](https://github.com/pulseq/pulseq/blob/master/matlab/%2Bmr/calcAdcSeg.m) from [pulseq](https://github.com/pulseq/pulseq/) saves in `pypulseq/tests/expected_output/pulseq_calcAdcSeg.txt`.
Reference to discussion #194.

PS. The repository for this repository is different from that in discussion in #194, but the code is the same. It is on github.com and hopefully cleaner.

2024-08-27 12:02 UTC, FrankZijlstra requested changes
Looks good in general. I marked a few inefficient bits of code and some typos that need changing.

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +    system.' and divisible by system.adcSamplesDivisor to be
Missing field name for `system.'`

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +        If 'mode' is not 'shorthen' or 'lengthen'.
Typo: shorten

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +            )
This section has very bad performance and huge memory usage for numbers with a large number of factors (e.g. 8192).

Replace with:
```
num_segments_candids = set()
for k in range(1, len(adc_seg_primes)+1):
    num_segments_candids |= set(math.prod(perm) for perm in itertools.combinations(adc_seg_primes, k))
```

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +                num_segments = candid
Change to `for num_segments in sorted(num_segments_candids)` to work with change above, and remove unnecessary line 171.

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +        else:  # Only one pollible solution
Typo: possible

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +        # Does output already fullfills contraints?
Typo: fulfill constraints

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +    # Validate contraints
Typo: constraints

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +                n //= i
Replace with the following to avoid unnecessary looping:
```
    i = 3
    while i * i <= n:
        while n % i == 0:
            factors.append(i)
            n //= i
        i += 2
```

2024-08-27 12:02 UTC, FrankZijlstra commented on pypulseq/make_adc.py
> +        The total number of samples can either be shortened or legthend to match the constraints.
Typo: Lengthened

2024-09-03 10:34 UTC, merged

2024-09-03 10:50 UTC, felixlandmeyer commented
@FrankZijlstra Thanks for the review! The new calculation of num_segments_candids speeds up the code a lot. And sorry for the typos.